## docker-compose.yml
## https://docs.docker.com/compose/compose-file/compose-file-v3/
---
version: "3"

services:
  webapp:
    #image: ghcr.io/kdavjd/rectification:latest
    build: .
    restart: always
    ports:
      - "127.0.0.1:18090:8080"

#    environment:
#      - FLASK_DEBUG=1
